### ISSUE TITLE
Installation of the package failed because of mediapipe

### ISSUE THREAD

**Issue by spheex** [multitel-ai/nsw-da-object-detection#21]
Hi.

I tried to install the package using the provided command:

`pip install -r requirements.txt`

It returned the following error:

```
ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.0 (from versions: 0.10.13, 0.10.14)
ERROR: No matching distribution found for mediapipe==0.10.0
```

Here is what I found on PyPi:

[https://pypi.org/project/mediapipe/0.10.0/](https://pypi.org/project/mediapipe/0.10.0/)

Installing 0.10.14 went well.

My configuration:

Windows 11
Python 3.12
Virgin conda environment, except for Python and Pip

**Comment by spheex** [comment]
I actually also got an error with the installation of xformers:

```
Collecting xformers==0.0.21 (from -r .\requirements.txt (line 7))
  Downloading xformers-0.0.21.tar.gz (22.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.3/22.3 MB 16.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\533288\AppData\Local\Temp\pip-install-wgi_t2fm\xformers_9de2cf92ef864a5dbf989ec3d6973ded\setup.py", line 23, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by fennecinspace** [comment]
Hello the issue should be solved, CIA was still in dev so some tinkering on the user's side maybe needed.
